# Site
name: 'Rizwan Ye'
description: 'A collection of articles that I write about the future of the economy and technology'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: "https://rizzwan.com"
baseurl: "/blog"
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    rizwan:
      name:           Rizwan Ye
      site:           https://rizzwan.com/
      avatar:         /assets/images/avatar1.jpeg
      bio:            "Degree in AI and Data Analytics"
      
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: rizwan
      avatar: /assets/images/avatar1.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
